apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projects.config.openshift.io
spec:
  group: config.openshift.io
  scope: Cluster
  version: v1
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  subresources:
    status: {}